In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Dataset=pd.read_csv("C:\\Users\\Administrator\\Downloads\\WineQT.csv")

In [3]:
Dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4

In [4]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB


In [5]:
Dataset.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000   
mean        8.311111          0.531339     0.268364        2.532152   
std         1.747595          0.179633     0.196686        1.355917   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.392500     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.100000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000   
mean      0.086933            15.615486             45.914698     0.996730   
std       0.047267            10.250486             32.782130     0.001925   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             21.000000     0.995570   
50%       0.079000            13.000000             37.000000     0.996680   
75%       0.090000            21.000000             61.000000     0.997845   
max       0.611000            68.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality           Id  
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000  
mean      3.311015     0.657708    10.442111     5.657043   804.969379  
std       0.156664     0.170399     1.082196     0.805824   463.997116  
min       2.740000     0.330000     8.400000     3.000000     0.000000  
25%       3.205000     0.550000     9.500000     5.000000   411.000000  
50%       3.310000     0.620000    10.200000     6.000000   794.000000  
75%       3.400000     0.730000    11.100000     6.000000  1209.500000  
max       4.010000     2.000000    14.900000     8.000000  1597.000000

In [6]:
Dataset.isnull()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             False             False        False           False      False   
1             False             False        False           False      False   
2             False             False        False           False      False   
3             False             False        False           False      False   
4             False             False        False           False      False   
...             ...               ...          ...             ...        ...   
1138          False             False        False           False      False   
1139          False             False        False           False      False   
1140          False             False        False           False      False   
1141          False             False        False           False      False   
1142          False             False        False           False      False   

      free sulfur dioxide  total sulfur dioxide  density     pH  sulphates  \
0                   False                 False    False  False      False   
1                   False                 False    False  False      False   
2                   False                 False    False  False      False   
3                   False                 False    False  False      False   
4                   False                 False    False  False      False   
...                   ...                   ...      ...    ...        ...   
1138                False                 False    False  False      False   
1139                False                 False    False  False      False   
1140                False                 False    False  False      False   
1141                False                 False    False  False      False   
1142                False                 False    False  False      False   

      alcohol  quality     Id  
0       False    False  False  
1       False    False  False  
2       False    False  False  
3       False    False  False  
4       False    False  False  
...       ...      ...    ...  
1138    False    False  False  
1139    False    False  False  
1140    False    False  False  
1141    False    False  False  
1142    False    False  False  

[1143 rows x 13 columns]

In [7]:
Dataset.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [8]:
np.unique(Dataset[["quality"]])

array([3, 4, 5, 6, 7, 8], dtype=int64)

In [9]:
Dataset["quality"]=Dataset["quality"].astype(str)

In [10]:
Dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol quality  Id  
0      9.4       5   0  
1      9.8       5   1  
2      9.8       5   2  
3      9.8       6   3  
4      9.4       5   4

In [11]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   object 
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 116.2+ KB


In [12]:
IQR=Dataset["fixed acidity"].describe()[6]-Dataset["fixed acidity"].describe()[4]

In [13]:
IQR

2.0

In [14]:
c=0
for i in Dataset["fixed acidity"]:
    if (i>Dataset["fixed acidity"].describe()[6]+IQR or i<abs(Dataset["fixed acidity"].describe()[4]-IQR)):
        c+=1
print(c)

105


In [15]:
X=Dataset.iloc[:,0:11]

In [16]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1138     11.0  
1139      9.5  
1140     10.5  
1141     11.2  
1142     10.2  

[1143 rows x 11 columns]

In [17]:
y=Dataset[["quality"]]

In [18]:
y

quality
0          5
1          5
2          5
3          6
4          5
...      ...
1138       6
1139       6
1140       5
1141       6
1142       5

[1143 rows x 1 columns]

In [121]:
from sklearn.model_selection import train_test_split

In [210]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [211]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
970             7.3             0.740         0.08             1.7      0.094   
72              8.1             0.575         0.22             2.1      0.077   
665            10.1             0.430         0.40             2.6      0.092   
584            12.9             0.500         0.55             2.8      0.072   
649             8.4             0.360         0.32             2.2      0.081   
...             ...               ...          ...             ...        ...   
1044            6.7             1.040         0.08             2.3      0.067   
1095            8.0             0.390         0.30             1.9      0.074   
1130            7.4             0.350         0.33             2.4      0.068   
860             7.9             0.570         0.31             2.0      0.079   
1126            7.5             0.520         0.40             2.2      0.060   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
970                  10.0                  45.0  0.99576  3.24       0.50   
72                   12.0                  65.0  0.99670  3.29       0.51   
665                  13.0                  52.0  0.99834  3.22       0.64   
584                   7.0                  24.0  1.00012  3.09       0.68   
649                  32.0                  79.0  0.99640  3.30       0.72   
...                   ...                   ...      ...   ...        ...   
1044                 19.0                  32.0  0.99648  3.52       0.57   
1095                 32.0                  84.0  0.99717  3.39       0.61   
1130                  9.0                  26.0  0.99470  3.36       0.60   
860                  10.0                  79.0  0.99677  3.29       0.69   
1126                 12.0                  20.0  0.99474  3.26       0.64   

      alcohol  
970       9.8  
72        9.2  
665      10.0  
584      10.9  
649      11.0  
...       ...  
1044     11.0  
1095      9.0  
1130     11.9  
860       9.5  
1126     11.8  

[857 rows x 11 columns]

In [212]:
y_train

quality
970        5
72         5
665        7
584        6
649        6
...      ...
1044       4
1095       5
1130       6
860        6
1126       6

[857 rows x 1 columns]

In [213]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
158             6.8             0.610         0.04             1.5      0.057   
1081            6.9             0.840         0.21             4.1      0.074   
291             7.0             0.580         0.12             1.9      0.091   
538             7.8             0.480         0.68             1.7      0.415   
367            12.5             0.600         0.49             4.3      0.100   
...             ...               ...          ...             ...        ...   
813            10.0             0.410         0.45             6.2      0.071   
213            10.6             0.830         0.37             2.6      0.086   
120             7.9             0.885         0.03             1.8      0.058   
1026            7.3             0.670         0.02             2.2      0.072   
667            10.2             0.440         0.58             4.1      0.092   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
158                   5.0                  10.0  0.99525  3.42       0.60   
1081                 16.0                  65.0  0.99842  3.53       0.72   
291                  34.0                 124.0  0.99560  3.44       0.48   
538                  14.0                  32.0  0.99656  3.09       1.06   
367                   5.0                  14.0  1.00100  3.25       0.74   
...                   ...                   ...      ...   ...        ...   
813                   6.0                  14.0  0.99702  3.21       0.49   
213                  26.0                  70.0  0.99810  3.16       0.52   
120                   4.0                   8.0  0.99720  3.36       0.33   
1026                 31.0                  92.0  0.99566  3.32       0.68   
667                  11.0                  24.0  0.99745  3.29       0.99   

        alcohol  
158    9.500000  
1081   9.233333  
291   10.500000  
538    9.100000  
367   11.900000  
...         ...  
813   11.800000  
213    9.900000  
120    9.100000  
1026  11.066667  
667   12.000000  

[286 rows x 11 columns]

In [214]:
y_test

quality
158        5
1081       6
291        5
538        6
367        6
...      ...
813        7
213        5
120        4
1026       6
667        7

[286 rows x 1 columns]

In [215]:
from sklearn.tree import DecisionTreeClassifier

In [128]:
DT=DecisionTreeClassifier()

In [129]:
DT.fit(X_train,y_train)

DecisionTreeClassifier()

In [130]:
P1=DT.predict(X_test)

In [131]:
P1

array(['4', '6', '6', '5', '5', '7', '5', '5', '5', '5', '7', '6', '6',
       '6', '6', '6', '6', '4', '5', '6', '7', '5', '5', '6', '5', '5',
       '7', '6', '5', '6', '5', '5', '7', '5', '5', '5', '5', '6', '6',
       '6', '6', '6', '6', '6', '5', '7', '5', '5', '5', '6', '6', '5',
       '5', '7', '6', '6', '5', '7', '7', '5', '5', '6', '6', '7', '7',
       '6', '8', '6', '6', '7', '5', '6', '5', '6', '6', '5', '5', '6',
       '5', '5', '6', '6', '5', '3', '5', '6', '5', '6', '8', '6', '5',
       '6', '5', '5', '5', '5', '5', '6', '6', '5', '6', '5', '5', '6',
       '5', '5', '6', '6', '6', '7', '7', '5', '5', '5', '3', '6', '6',
       '8', '5', '6', '5', '6', '5', '6', '5', '6', '6', '6', '5', '6',
       '5', '5', '7', '6', '5', '4', '5', '6', '5', '6', '6', '5', '5',
       '5', '7', '5', '5', '5', '5', '5', '6', '5', '6', '4', '6', '5',
       '5', '5', '7', '6', '5', '5', '6', '5', '7', '5', '6', '4', '6',
       '5', '6', '6', '6', '6', '5', '4', '6', '6', '6', '5', '6

In [132]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [133]:
Classification_Report=classification_report(y_test,P1)
print(Classification_Report)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.29      0.33      0.31         6
           5       0.63      0.62      0.63        96
           6       0.54      0.52      0.53        99
           7       0.46      0.50      0.48        26
           8       0.33      0.50      0.40         2

    accuracy                           0.55       229
   macro avg       0.38      0.41      0.39       229
weighted avg       0.56      0.55      0.56       229



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [134]:
Confusion_Matrix=confusion_matrix(y_test,P1)
print(Confusion_Matrix)

[[ 0  0  0  0  0  0]
 [ 0  2  2  1  1  0]
 [ 0  5 60 29  2  0]
 [ 2  0 33 51 11  2]
 [ 0  0  0 13 13  0]
 [ 0  0  0  0  1  1]]


In [135]:
Accuracy=accuracy_score(y_test,P1)
print(Accuracy)

0.5545851528384279


In [136]:
P2DT=DT.predict(X_train)

In [137]:
Accuracy2=accuracy_score(y_train,P2DT)
print(Accuracy2)

1.0


In [138]:
from sklearn.naive_bayes import GaussianNB

In [139]:
NB=GaussianNB()

In [140]:
NB.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [141]:
PNB=NB.predict(X_test)

In [142]:
PNB

array(['6', '5', '5', '4', '7', '7', '5', '5', '6', '5', '7', '6', '5',
       '6', '6', '5', '6', '6', '6', '6', '6', '5', '5', '6', '6', '5',
       '7', '6', '5', '6', '6', '6', '7', '6', '6', '5', '5', '6', '7',
       '4', '6', '5', '7', '5', '5', '5', '6', '6', '5', '6', '7', '5',
       '6', '5', '6', '7', '6', '6', '6', '6', '6', '6', '6', '6', '6',
       '6', '7', '6', '5', '6', '8', '6', '5', '6', '5', '5', '6', '6',
       '6', '6', '6', '6', '6', '5', '6', '6', '4', '6', '6', '6', '3',
       '6', '4', '5', '5', '5', '6', '6', '7', '6', '6', '6', '5', '6',
       '6', '5', '6', '7', '6', '8', '6', '5', '6', '6', '5', '5', '6',
       '7', '6', '5', '5', '5', '5', '4', '5', '6', '6', '6', '5', '7',
       '5', '5', '5', '6', '7', '3', '5', '6', '6', '6', '7', '6', '6',
       '5', '7', '6', '5', '6', '4', '5', '7', '6', '8', '5', '6', '6',
       '6', '6', '7', '6', '6', '5', '6', '6', '6', '6', '7', '6', '6',
       '5', '6', '6', '5', '6', '5', '5', '7', '5', '6', '5', '7

In [143]:
Confusion_Matrix=confusion_matrix(y_test,PNB)
print(Confusion_Matrix)

[[ 0  0  0  0  0  0]
 [ 0  0  4  2  0  0]
 [ 2  2 50 41  1  0]
 [ 0  5 12 68 12  2]
 [ 0  0  2  8 15  1]
 [ 0  0  0  0  2  0]]


In [144]:
Accuracy=accuracy_score(y_test,PNB)
print(Accuracy)

0.5807860262008734


In [145]:
P2NB=NB.predict(X_train)

In [146]:
Accuracy2=accuracy_score(y_train,P2NB)
print(Accuracy2)

0.5492341356673961


In [216]:
from sklearn.ensemble import RandomForestClassifier

In [217]:
RF=RandomForestClassifier()

In [218]:
RF.fit(X_train,y_train)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1480\3662798500.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RF.fit(X_train,y_train)


RandomForestClassifier()

In [219]:
PRF=RF.predict(X_test)

In [220]:
PRF

array(['5', '6', '5', '5', '5', '6', '5', '5', '6', '5', '7', '6', '6',
       '6', '5', '5', '6', '5', '5', '7', '6', '6', '5', '7', '5', '5',
       '7', '6', '5', '6', '5', '6', '7', '6', '5', '5', '6', '6', '6',
       '5', '6', '6', '6', '5', '5', '5', '5', '6', '5', '6', '7', '5',
       '5', '7', '6', '6', '6', '6', '5', '5', '5', '6', '6', '6', '6',
       '6', '6', '5', '5', '5', '6', '5', '5', '6', '5', '5', '5', '6',
       '5', '6', '5', '6', '6', '5', '5', '6', '5', '5', '6', '6', '5',
       '6', '5', '5', '5', '5', '5', '6', '5', '6', '6', '6', '5', '6',
       '5', '5', '6', '6', '6', '7', '7', '5', '5', '6', '5', '6', '6',
       '6', '6', '5', '5', '5', '5', '6', '5', '5', '6', '6', '5', '6',
       '5', '5', '7', '6', '7', '5', '5', '6', '5', '6', '7', '5', '6',
       '5', '6', '5', '5', '5', '5', '5', '6', '5', '6', '5', '6', '5',
       '5', '5', '7', '6', '5', '5', '6', '6', '7', '5', '6', '6', '6',
       '5', '6', '5', '6', '5', '5', '5', '7', '6', '6', '5', '6

In [221]:
Confusion_Matrix=confusion_matrix(y_test,PRF)
print(Confusion_Matrix)

[[ 0  4  3  0  0]
 [ 0 96 23  2  0]
 [ 0 33 83  5  0]
 [ 0  1 12 21  0]
 [ 0  0  3  0  0]]


In [222]:
Accuracy=accuracy_score(y_test,PRF)
print(Accuracy)

0.6993006993006993


In [223]:
P2RF=RF.predict(X_train)

In [224]:
Accuracy2=accuracy_score(y_train,P2RF)
print(Accuracy2)

1.0


In [156]:
from sklearn.svm import SVC

In [157]:
SVM=SVC()

In [158]:
SVM.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [159]:
PSVM=SVM.predict(X_test)

In [160]:
PSVM

array(['6', '5', '5', '6', '6', '6', '6', '5', '6', '5', '5', '6', '6',
       '6', '6', '5', '6', '6', '6', '6', '6', '6', '5', '6', '6', '5',
       '6', '6', '6', '6', '6', '6', '6', '6', '6', '5', '6', '6', '6',
       '5', '6', '6', '6', '6', '6', '6', '6', '6', '5', '6', '6', '6',
       '6', '6', '5', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
       '5', '6', '6', '5', '6', '6', '6', '5', '6', '6', '6', '6', '6',
       '6', '6', '5', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
       '6', '5', '5', '6', '5', '5', '6', '6', '6', '6', '6', '5', '6',
       '5', '5', '6', '6', '6', '6', '6', '5', '6', '6', '5', '5', '6',
       '6', '6', '5', '6', '5', '5', '5', '6', '6', '6', '6', '5', '6',
       '5', '5', '7', '6', '5', '6', '5', '6', '6', '6', '6', '6', '6',
       '5', '6', '5', '5', '6', '5', '5', '6', '6', '6', '6', '6', '6',
       '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
       '5', '6', '6', '6', '6', '5', '5', '6', '5', '6', '6', '6

In [161]:
Confusion_Matrix=confusion_matrix(y_test,PSVM)
print(Confusion_Matrix)

[[ 0  2  4  0  0]
 [ 0 41 55  0  0]
 [ 0 12 87  0  0]
 [ 0  1 24  1  0]
 [ 0  0  2  0  0]]


In [162]:
Accuracy=accuracy_score(y_test,PSVM)
print(Accuracy)

0.5633187772925764


In [163]:
P2SVM=SVM.predict(X_train)

In [164]:
Accuracy2=accuracy_score(y_train,P2SVM)
print(Accuracy2)

0.4934354485776805
